### ISSUE TITLE
リポジトリをリスト化するページのテンプレート等

### ISSUE THREAD

**Issue by fuyutsuki** [MCBEDev-JPN/mcbe-jpn.github.io#10]
## TODO
- [ ] リポジトリリストページ作成
- [ ] リポジトリ登録テンプレート作成
- [ ] リポジトリ登録方法ページ作成

**Comment by kazuemon** [comment]
このリポジトリは今後 MCBEDev-JPN/dev.mcbe.jp に移行となります。
移行と同時にこれらのIssueも解消させる予定です。

**Comment by kazuemon** [comment]
方針変更によりリポジトリリスト計画は終了
